/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "var(--color-primary-fixed)",
        "secondary": "var(--color-secondary)",
        "background": "var(--color-background)",
        "surface-container": "var(--color-surface-container)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "error-container": "var(--color-error-container)",
        "primary-container": "var(--color-primary-container)",
        "on-background": "var(--color-on-background)",
        "outline-variant": "var(--color-outline-variant)",
        "outline": "var(--color-outline)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "inverse-primary": "var(--color-inverse-primary)",
        "surface-variant": "var(--color-surface-variant)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-error": "var(--color-on-error)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "secondary-container": "var(--color-secondary-container)",
        "tertiary": "var(--color-tertiary)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "surface": "var(--color-surface)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-surface": "var(--color-on-surface)",
        "on-error-container": "var(--color-on-error-container)",
        "surface-bright": "var(--color-surface-bright)",
        "on-secondary": "var(--color-on-secondary)",
        "on-primary": "var(--color-on-primary)",
        "on-tertiary": "var(--color-on-tertiary)",
        "error": "var(--color-error)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "primary": "var(--color-primary)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-primary-container": "var(--color-on-primary-container)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "inverse-surface": "var(--color-inverse-surface)",
        "surface-tint": "var(--color-surface-tint)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "surface-container-high": "var(--color-surface-container-high)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "stack-lg": "32px",
        "margin-mobile": "16px",
        "unit": "4px",
        "container-max": "1440px",
        "margin-desktop": "40px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "container-padding": "32px",
        "max-width-desktop": "1440px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "label-md": ["Geist"],
        "body-lg": ["Inter"],
        "headline-md": ["Geist"],
        "headline-lg": ["Geist"],
        "body-sm": ["Inter"],
        "label-sm": ["Geist"],
        "headline-xl": ["Geist"],
        "headline-lg-mobile": ["Geist"],
        "inter": ["Inter", "sans-serif"],
        "geist": ["Geist", "sans-serif"],
        "sora": ["Sora", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
